# Generated by Django 4.2.7 on 2023-11-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('student_id', models.CharField(max_length=20)),
                ('add', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Student Datas',
            },
        ),
    ]
